encoding: utf-8

env: production

exclude: ['package-lock.json','rss.xml','copy','buildspec.yml', 'Gemfile','Gemfile.lock','Gruntfile.js', 'package.json', 'readme.md', 'sftpCache.json' ,'node_modules','us-army-homepage','armydotmil.github.io']
    
plugins:
  - octopress-minify-html
  - octopress-autoprefixer
  - jekyll-minifier

sass:
  sass_dir: _scss
  style: compressed
  
jekyll-minifier:
  exclude: ['*.html','*.css','*.scss']

title: StandTo

algolia:
  application_id: 'OXO7ZR0CL9'
  index_name: jekyll
  search_only_api_key: b48203d800b4d24ce891fa762af1b714
  files_to_exclude: 
    - /archive/index.html
    - /archives/index.html
  extensions_to_include:
    - html
  nodes_to_index: 'h1, span.date, span.st-byline'
  settings:
    searchableAttributes:
      - year
      - month
      - file
      - unordered(title)
      - content
    attributesToHighlight:
      - file
      - metaTitle
      - month
      - year