# setting env to production will minify the html
#env: production
env: dev

exclude: ['Gruntfile.js', 'package.json', 'readme.md', 'sftpCache.json' ,'node_modules','us-army-homepage']
    
plugins:
  - octopress-minify-html
  
sass:
  sass_dir: _scss
  style: compressed

title: Army Families

